version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"  # VNC port for debugging
    environment:
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_MAX_SESSIONS=1
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped

  # For ARM devices (Apple Silicon, Raspberry Pi, etc.), use this instead:
  # selenium:
  #   image: seleniarm/standalone-chromium:latest
  #   shm_size: 2gb
  #   ports:
  #     - "4444:4444"
  #   restart: unless-stopped